[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "smartplaybuddy"
version = "0.1.0"
description = "A Python client for SmartPlayBuddy gamepad control."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "websockets",
    "pyautogui",
    "keyring",
    "windows-capture",
    "pywebview",
    "PyQt6",
    "dxcam[cv2]",
    "numpy",
    "Pillow",
]

[tool.setuptools.packages.find]
where = ["src"]

[project.scripts]
smtplay = "smartplaybuddy.client:main"
smtplay-mod = "smartplaybuddy.mod:main"
smtplay-debug = "smartplaybuddy.ui.debugger:main"
